### PR TITLE
Fixed Sound Skipping when BPM is around 120

### LINKED ISSUE #35: Click isn't always playing
The click doesn't seem to play if the click is still active.

For example set the BPM to 120, you will see that only every other click sounds, the click should sound on every beat.

### PR DESCRIPTION
**Pull request by iamrajatg**
closes #35

### CODE REVIEW

File: script.js [hunk 1]
```diff
@@ -53,7 +53,10 @@ function move(width = 1) {
 // cahnge color and play sound when progress bar is 100% width
 function endProgress() {
 	metronome.style.background = getRandomColor();
-	if (!mute) clickSound.play();
+	if (!mute) {
+		//load sound so that it resets on every beat
+		clickSound.load()
```
Comment (YasiOnFire) [inline script.js:58]: if i may suggest, You don't need to load the sound again, just set the currentTime to 0 to rewind it.

**Review by YasiOnFire — COMMENTED** [review]
if i may suggest, You don't need to load the sound again, just set the currentTime to 0 to rewind it.
